const nodemailer = require("nodemailer");



const LOGO_URL =
"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhXsfCtQ07icafhDTAW7Y17qVGYgNzky_kaqsKugCvi4ewKepdc9k7TYXOD-YrWA38oGxqsdnNtqXYWFw_3ze0ngn78_puqlb3c647OHdFNT7UgPL72_Im5zdJB0L-YT3PQQTzi7QpD68lm-OXiZsAMnymD3OgeDzLjwmhrkkLjwhXFPfSudsCiF7Pg1Yib/s2560/1000070116.png";





const transporter = nodemailer.createTransport({

    host:
    process.env.SMTP_HOST || "smtp.zoho.in",


    port:
    Number(process.env.SMTP_PORT) || 465,


    secure:
    true,


    auth:{


        user:
        process.env.EMAIL,


        pass:
        process.env.PASSWORD

    },


    connectionTimeout:30000,

    greetingTimeout:30000,

    socketTimeout:30000,


    tls:{

        rejectUnauthorized:false

    }


});








async function verifySMTP(){


try{


await transporter.verify();


console.log(
"✅ SMTP Connection Ready"
);


}


catch(error){


console.error(
"❌ SMTP Verification Failed:",
error.message
);


}



}





verifySMTP();









function textValue(value){


if(!value)
return "";


if(typeof value==="object"){

return String(
value.message ||
value.text ||
value.body ||
""
);

}


return String(value);


}








function escapeHtml(value){


return textValue(value)

.replace(/&/g,"&amp;")

.replace(/</g,"&lt;")

.replace(/>/g,"&gt;")

.replace(/"/g,"&quot;")

.replace(/'/g,"&#039;");


}









function stripHtml(value){


return textValue(value)

.replace(/<style[\s\S]*?<\/style>/gi,"")

.replace(/<script[\s\S]*?<\/script>/gi,"")

.replace(/<br\s*\/?>/gi,"\n")

.replace(/<\/p>/gi,"\n")

.replace(/<[^>]*>/g,"")

.replace(/&nbsp;/gi," ")

.trim();


}









function cleanSignature(text){


return textValue(text)

.replace(
/Regards,[\s\S]*?(InternovaTech Support Team|InternovaTech Team|InternovaTech Support)/gi,
""
)

.trim();


}









function createTemplate(content){


return `

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<meta name="viewport" content="width=device-width,initial-scale=1">


</head>



<body style="
margin:0;
padding:0;
background:#f4f7fb;
font-family:Arial,Helvetica,sans-serif;
">



<table width="100%" cellpadding="0" cellspacing="0">

<tr>

<td align="center" style="padding:20px;">



<table width="600" cellpadding="0" cellspacing="0"
style="
max-width:600px;
background:#ffffff;
border-radius:16px;
overflow:hidden;
">





<tr>

<td align="center"

style="
background:#111827;
padding:25px;
">


<img

src="${LOGO_URL}"

width="85"

style="
border-radius:50%;
display:block;
"

alt="InternovaTech"


/>



<h2 style="
color:#ffffff;
margin:15px 0 5px;
">

InternovaTech 🚀

</h2>



<p style="
color:#d1d5db;
font-size:14px;
">

AI Support Assistant

</p>



</td>

</tr>








<tr>

<td style="
padding:30px;
color:#374151;
font-size:15px;
line-height:1.7;
">


${content}



</td>

</tr>








<tr>

<td align="center"

style="
background:#111827;
padding:20px;
color:#ffffff;
font-size:13px;
">


<b>
InternovaTech
</b>


<br>


info@internovatech.in


<br>


www.internovatech.in



<br><br>


<span style="
font-size:11px;
color:#d1d5db;
">

Automated response generated by InternovaTech AI Support Assistant.

</span>


</td>


</tr>



</table>


</td>


</tr>


</table>



</body>

</html>

`;

}









async function sendMail({

to,

subject,

text,

inReplyTo=null

}){



let attempts=0;


const maxAttempts=3;



while(attempts < maxAttempts){



try{



attempts++;




let cleanContent =
cleanSignature(text);




if(!cleanContent){


cleanContent =
"Hello,\n\nThank you for contacting InternovaTech. We have received your message.";

}





const html =
createTemplate(`

<p>
Hello,
</p>


<p>
${escapeHtml(cleanContent).replace(/\n/g,"<br>")}
</p>



<br>


<p>
Regards,<br>

<b>
InternovaTech Support Team
</b>

</p>

`);







const mailOptions={


from:{


name:"InternovaTech Support",

address:process.env.EMAIL


},



to,


subject,



text:
stripHtml(cleanContent),



html,



headers:{}

};







if(inReplyTo){


mailOptions.headers["In-Reply-To"]
=
inReplyTo;


mailOptions.headers["References"]
=
inReplyTo;


}






const info =
await transporter.sendMail(
mailOptions
);



console.log(
"📤 Email Sent:",
info.messageId
);



return info;




}

catch(error){



console.error(
`SMTP Attempt ${attempts} Failed:`,
error.message
);



if(attempts >= maxAttempts){

throw error;

}



await new Promise(

resolve=>setTimeout(resolve,5000)

);


}



}



}






module.exports =
sendMail;