const nodemailer = require("nodemailer");



const transporter = nodemailer.createTransport({

    host: process.env.SMTP_HOST,

    port: Number(process.env.SMTP_PORT),

    secure: true,

    auth:{
        user: process.env.EMAIL,
        pass: process.env.PASSWORD
    }

});





const LOGO_URL =
"https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhXsfCtQ07icafhDTAW7Y17qVGYgNzky_kaqsKugCvi4ewKepdc9k7TYXOD-YrWA38oGxqsdnNtqXYWFw_3ze0ngn78_puqlb3c647OHdFNT7UgPL72_Im5zdJB0L-YT3PQQTzi7QpD68lm-OXiZsAMnymD3OgeDzLjwmhrkkLjwhXFPfSudsCiF7Pg1Yib/s2560/1000070116.png";








function toMessageText(value){

if(value === null || value === undefined){
return "";
}

if(typeof value === "object"){
return String(value.message || value.text || value.body || "");
}

return String(value);

}


function escapeHtml(value){

return toMessageText(value)
.replace(/&/g,"&amp;")
.replace(/</g,"&lt;")
.replace(/>/g,"&gt;")
.replace(/"/g,"&quot;")
.replace(/'/g,"&#039;");

}


function stripHtml(value){

return toMessageText(value)
.replace(/<style[\s\S]*?<\/style>/gi,"")
.replace(/<script[\s\S]*?<\/script>/gi,"")
.replace(/<br\s*\/?>/gi,"\n")
.replace(/<\/p>/gi,"\n\n")
.replace(/<\/li>/gi,"\n")
.replace(/<[^>]*>/g,"")
.replace(/&nbsp;/gi," ")
.replace(/&amp;/gi,"&")
.replace(/&lt;/gi,"<")
.replace(/&gt;/gi,">")
.replace(/&quot;/gi,"\"")
.replace(/&#039;/gi,"'")
.replace(/\n{3,}/g,"\n\n")
.trim();

}


function removeDuplicateSignature(value){

return toMessageText(value)
.replace(/Regards,[\s\S]*?(InternovaTech Support Team|InternovaTech Team)/gi,"")
.trim();

}


function createTemplate(content){


return `

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">


</head>



<body style="
margin:0;
padding:0;
background:#f4f7fb;
font-family:Arial,Helvetica,sans-serif;
">


<table width="100%" cellpadding="0" cellspacing="0">

<tr>

<td align="center" style="padding:25px;">



<table width="600" cellpadding="0" cellspacing="0"
style="
background:#ffffff;
border-radius:14px;
overflow:hidden;
box-shadow:0 5px 20px rgba(0,0,0,0.08);
">


<!-- HEADER -->

<tr>

<td align="center"
style="
background:#111827;
padding:25px;
">


<img 
src="${LOGO_URL}"
width="85"
style="
display:block;
margin:auto;
border-radius:50%;
"
alt="InternovaTech Logo"
/>



<h2 style="
color:white;
margin:12px 0 5px;
font-size:24px;
">

InternovaTech 🚀

</h2>



<p style="
color:#d1d5db;
margin:0;
font-size:14px;
">

AI Support Assistant

</p>



</td>

</tr>







<!-- BODY -->

<tr>

<td style="
padding:30px;
color:#374151;
font-size:15px;
line-height:1.7;
">


${content}



<br>


<p>

Regards,<br>

<b>
InternovaTech Support Team
</b>

</p>



</td>

</tr>







<!-- FOOTER -->


<tr>

<td align="center"
style="
background:#111827;
color:white;
padding:20px;
font-size:13px;
line-height:1.6;
">


<b>
InternovaTech
</b>


<br>


Email:
info@internovatech.in


<br>


Website:
www.internovatech.in



<br><br>


<span style="
font-size:11px;
color:#d1d5db;
">

This is an automated response generated by InternovaTech AI Support Assistant.

</span>



</td>


</tr>





</table>



</td>

</tr>


</table>


</body>

</html>

`;

}









async function sendMail({

to,

subject,

text,

inReplyTo=null


}){


try{


let cleanContent =
removeDuplicateSignature(text);


if(!cleanContent){


cleanContent =
"Hello,\n\nThank you for contacting InternovaTech. We have received your message and will assist you shortly.";


}







let html;


if(
cleanContent.includes("<p") ||
cleanContent.includes("<h2") ||
cleanContent.includes("<div") ||
cleanContent.includes("<ul") ||
cleanContent.includes("<ol")
){

html =
createTemplate(cleanContent);


}
else{


html =
createTemplate(
`
<p>
Hello,
</p>

<p>
${escapeHtml(cleanContent).replace(/\n/g,"<br>")}
</p>
`
);


}







const mailOptions={


from:{

name:"InternovaTech Support",

address:process.env.EMAIL

},



to,


subject,



text:
stripHtml(cleanContent),



html,



headers:{}


};






if(inReplyTo){


mailOptions.headers["In-Reply-To"]
=
inReplyTo;


mailOptions.headers["References"]
=
inReplyTo;


}







const info =
await transporter.sendMail(
mailOptions
);



console.log(
"📤 Email Sent:",
info.messageId
);



return info;



}

catch(error){


console.error(
"❌ Mail Send Error:",
error
);


throw error;


}


}





module.exports = sendMail;
